export var colorPrimary = "var(--cl-primary,#5c50bb)";
export var colorSecondary = "var(--cl-secondary,#efedfd)";
export var colorDefaultBg = "var(--cl-default-bg,#f7f7f7)";
export var colorBorder = "var(--cl-border, #a8a8a8)";
export var colorSeparator = "var(--cl-separator, #e1e1e1";
export var white = "white";
export var black = "black";
export var black12 = "rgba(0, 0, 0, 0.12)";
export var disabled = "rgba(0, 0, 0, 0.35)";
//# sourceMappingURL=colors.js.map